
tasks:
  - name: eslint
    init: yarn add eslint
  - name: servidor
    init: yarn
    command: yarn start

ports:
  - port: 3000
    onOpen: open-browser

vscode:
  extensions:
    - dbaeumer.vscode-eslint
